---
title: "Replication of Miller and Weinberg (2017)"
author: "Kohei Kawaguchi"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE,
  fig.width = 10, 
  fig.height = 6
)

# Load required packages
devtools::load_all(".")
library(foreach)
library(magrittr)
library(ggplot2)
```

# Reading

Miller, Nathan H., and Matthew C. Weinberg. "Understanding the Price Effects of the MillerCoors Joint Venture." Econometrica 85, no. 6 (2017): 1763–91. https://doi.org/10.3982/ECTA13333.


# Estiamte

Use simulated data from our implementation.

Develop functions to:
- Extract demand and marginal cost shocks
- Regress them on demand and cost covariates 
- Extract demand and marginal cost residuals as well as the linear parameters
- Compute the empirical moments based on the residuals
- Compute the objective function as a function of the non-linear parameters based on the moments
- Minimize the objective function to get the estimates

Then, test your code by
- Checking that the elicited demand and marginal cost residuals perfectly match with the true residuals
- Checking that the objective function is marginally minimized at the true value along each non-linear parameters
- Checking that the estimates are close to the true values

## Remarks

When you do so, follow the workflow and coding rules as specified in https://www.notion.so/koheikawaguchi/Tutorial-Page-18e6acdb3c2e8036af3df134e088f9dd

Specifically, make sure to start with testing functions from the bottom to the top. Then, you move on to main execution files. The results will be saved and read from an Rmarkdown file to report.

