--- 
title: "ECON5630 Topics in Empirical Industrial Organization"
author: "Kohei Kawaguchi"
date: 'Last updated: `r Sys.Date()`'
output:
  pdf_document: default
  html_document:
    df_print: paged
bibliography:
- PhDIO.bib
- PhDIO2.bib
- packages.bib
description: Thie is a lecture note for ECON5630 at Hong Kong University of Science and Technology. 
documentclass: book
highlight: espresso
link-citations: yes
csl: plain.csl
site: bookdown::bookdown_site
---

# Syllabus

## Instructor Information

- Instructor:
    - Name: Kohei Kawaguchi.
    - Office hour: LSK6070, Tue 17:00-18:00, Zoom link for office hour is provided in Canvas.
- All questions related to the class have to be publicly asked on slack rather than being privately asked in e-mail. The instructor usually does not reply in the evening, weekends, and holidays.

    

## General Information

### Class Time

- Date: Tue, Thu.
- Time: 9:00-10:50.
- Venue: Online.

### Description

- This is a PhD-level course for empirical industrial organization. This course covers various econometric methods used in industrial organization that is often referred to as the structural estimation approach. These methods have been gradually developed since 1980s in parallel with the modernization of industrial organization based on the game theory and now widely applied in antitrust policy, business strategy, and neighboring fields such as labor economics and international economics.

- This course presumes a good understanding of PhD-level microeconomics and microeconometrics. Participants are expected to understand at least UG-level industrial organization. This course requires participants to write programs mostly in R and sometimes in C++ to implement various econometric methods. In particular, all assignments will involve such a non-trivial programming task. Even though the understanding of these programming languages is not a prerequisite, a sharp learning curve will be required. Some experience in other programming languages will help. Audit without a credit is not admitted for students.


### Expectation and Goals

- The goal of this course is to learn and practice econometric methods for empirical industrial organization. The lecture covers the econometric methods that have been developed between 80s and 00s to estimate primitive parameters governing imperfect competition among firms,  such as production and cost function estimation, demand function estimation, merger simulation, entry and exit analysis, and dynamic decision models. The lecture also covers various new methods to recover model primitives in certain mechanisms such as auction, matching, network, and bargaining. The emphasis is put on the former group of methods, because they are the basis for other new methods. Participants will not only understand the theoretical background of the methods but also become able to implement these methods from scratches by writing their own programs. I will briefly discuss the latter class of new methods through reading recent papers. The participants will become able to understand and use these new methods.  

## Required Environment

- Participants should bring their laptop to the class. We have enough extension codes for students. The laptop should have sufficient RAM (at least $\ge$ 8GB, $\ge$ 16GB is recommended) and CPU power (at least Core i5 grade, Core i7 grade is recommended). Participants are fully responsible for their hardware issues. Operating System can be arbitrary. 
- Please install the following software by the first lecture. Technical issues related to the installment should be resolved by yourself, because it depends on your local environment. If you had an error, copy and paste the error message on a search engine, and find a solution. This solves 99.9% of the problems.
    - R: [https://www.r-project.org/](https://www.r-project.org/)
    - RStudio: [https://www.rstudio.com/](https://www.rstudio.com/)
    - LaTeX: 
        - MikTex [https://miktex.org/](https://miktex.org/)
        - TeXLive [https://www.tug.org/texlive/](https://www.tug.org/texlive/)
        - MacTeX [http://www.tug.org/mactex/](http://www.tug.org/mactex/)



## Evaluation

- Assignments (90): In total 9 homework are assigned. Each homework involves the implementation of the methods covered in the class. Each homework has 10 points. The working hour for each homework will be around 10-20 hours.
- Presentation (10): Toward the end of the semester, a paper in industrial organization is randomly assigned to each participant. Each participant makes a presentation within 20 pages and records 30 minutes presentation.
- Grading is based on the absolute scores: A+ with more than 90 points, A with more than 85 points, A- with more than 80 points, B+ with more than 70 points, B with more than 60 points, B- with more than 50 points and C otherwise. 


## Academic Integrity

Without academic integrity, there is no serious learning. Thus you are expected to hold the highest standard of academic integrity in the course. You are encouraged to study and do homework in groups. However, no cheating, plagiarism will be tolerated. Anyone caught
cheating, plagiarism will fail the course. Please make sure adhere to the HKUST Academic
Honor Code at all time (see http://www.ust.hk/vpaao/integrity/).


## Schedule

- Introduction to structural estimation, R and RStudio 
- Production function estimation I
- Production function estimation II
- Demand function estimation I
- Demand function estimation II
- Merger Analysis 
- Entry and Exit 
- Single-Agent Dynamics I 
- Single-Agent Dynamics II, I change date due to my business trip 
- Dynamic Game I 
- Dynamic Game II 
- Auction 
- Presentations 


## Course Materials

### R and RStudio

- Grolemund, G., 2014, Hands-On Programming with R, O'Reilly.
    - Free online version is available: [https://rstudio-education.github.io/hopr/](https://rstudio-education.github.io/hopr/).
- Wickham, H., & Grolemund, G., 2017, R for Data Science, O'Reilly.
    - Free online version is available: [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/).
- Boswell, D., & Foucher, T., 2011, The Art of Readable Code: Simple and Practical Techniques for Writing Better Code, O'Reilly.

### Handbook Chapters

- Ackerberg, D., Benkard, C., Berry, S., & Pakes, A. (2007). "Econometric tools for analyzing market outcomes". Handbook of econometrics, 6, 4171-4276.
- Athey, S., & Haile, P. A. (2007). "Nonparametric approaches to auctions". Handbook of
Econometrics, 6, 3847-3965.
- Berry, S., & Reiss, P. (2007). "Empirical models of entry and market structure". Handbook of Industrial Organization, 3, 1845-1886.
- Bresnahan, T. F. (1989). "Empirical studies of industries with market power". Handbook of
Industrial Organization, 2, 1011-1057.
- Hendricks, K., & Porter, R. H. (2007). "An empirical perspective on auctions". Handbook of
Industrial Organization, 3, 2073-2143.
- Matzkin, R. L. (2007). "Nonparametric identification". Handbook of Econometrics, 6, 5307-5368.
- Newey, W. K., & McFadden, D. (1994). "Large sample estimation and hypothesis testing". Handbook of Econometrics, 4, 2111-2245.
- Reiss, P. C., & Wolak, F. A. (2007). "Structural econometric modeling: Rationales and examples from industrial organization". Handbook of Econometrics, 6, 4277-4415.

### Books

- Train, K. E. (2009). Discrete Choice Methods with Simulation, Cambridge university press.
- Davis, P., & Garces, E. (2010). Quantitative Techniques for Competition and Antitrust Analysis, Princeton University Press.
- Tirole, J. (1988). The Theory of Industrial Organization, The MIT Press.

### Papers

- The list of important papers are occasionally given during the course.



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
