<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 6 Hypothesis Testing in R | ECON 6120I Topics in Empirical Industrial Organization</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 6 Hypothesis Testing in R | ECON 6120I Topics in Empirical Industrial Organization />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Hypothesis Testing in R | ECON 6120I Topics in Empirical Industrial Organization />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Kohei Kawaguchi">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="estimation-of-mean-in-r.html">
<link rel="next" href="simple-regression-in-r.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ECON6120I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Syllabus</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#instructor-information"><i class="fa fa-check"></i><b>1.1</b> Instructor Information</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#general-information"><i class="fa fa-check"></i><b>1.2</b> General Information</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#class-time"><i class="fa fa-check"></i><b>1.2.1</b> Class Time</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#description"><i class="fa fa-check"></i><b>1.2.2</b> Description</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#expectation-and-goals"><i class="fa fa-check"></i><b>1.2.3</b> Expectation and Goals</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#required-environment"><i class="fa fa-check"></i><b>1.3</b> Required Environment</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#evaluation"><i class="fa fa-check"></i><b>1.4</b> Evaluation</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#academic-integrity"><i class="fa fa-check"></i><b>1.5</b> Academic Integrity</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>1.6</b> Schedule</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#course-materials"><i class="fa fa-check"></i><b>1.7</b> Course Materials</a><ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.7.1</b> R and RStudio</a></li>
<li class="chapter" data-level="1.7.2" data-path="index.html"><a href="index.html#handbook-chapters"><i class="fa fa-check"></i><b>1.7.2</b> Handbook Chapters</a></li>
<li class="chapter" data-level="1.7.3" data-path="index.html"><a href="index.html#books"><i class="fa fa-check"></i><b>1.7.3</b> Books</a></li>
<li class="chapter" data-level="1.7.4" data-path="index.html"><a href="index.html#papers"><i class="fa fa-check"></i><b>1.7.4</b> Papers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#structural-estimation-and-counterfactual-analysis"><i class="fa fa-check"></i><b>2.1</b> Structural Estimation and Counterfactual Analysis</a><ul>
<li class="chapter" data-level="2.1.1" data-path="intro.html"><a href="intro.html#example"><i class="fa fa-check"></i><b>2.1.1</b> Example</a></li>
<li class="chapter" data-level="2.1.2" data-path="intro.html"><a href="intro.html#recap"><i class="fa fa-check"></i><b>2.1.2</b> Recap</a></li>
<li class="chapter" data-level="2.1.3" data-path="intro.html"><a href="intro.html#historical-remark"><i class="fa fa-check"></i><b>2.1.3</b> Historical Remark</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#setting-up-the-environment"><i class="fa fa-check"></i><b>2.2</b> Setting Up The Environment</a><ul>
<li class="chapter" data-level="2.2.1" data-path="intro.html"><a href="intro.html#rstudio-project"><i class="fa fa-check"></i><b>2.2.1</b> RStudio Project</a></li>
<li class="chapter" data-level="2.2.2" data-path="intro.html"><a href="intro.html#basic-programming-in-r"><i class="fa fa-check"></i><b>2.2.2</b> Basic Programming in R</a></li>
<li class="chapter" data-level="2.2.3" data-path="intro.html"><a href="intro.html#basic-statistical-analysis"><i class="fa fa-check"></i><b>2.2.3</b> Basic Statistical Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html"><i class="fa fa-check"></i><b>3</b> Descriptive Analysis in R</a><ul>
<li class="chapter" data-level="3.1" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#qualitative-data"><i class="fa fa-check"></i><b>3.1</b> Qualitative Data</a><ul>
<li class="chapter" data-level="3.1.1" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#frequency-distribution"><i class="fa fa-check"></i><b>3.1.1</b> Frequency Distribution</a></li>
<li class="chapter" data-level="3.1.2" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#relative-frequency-distribution"><i class="fa fa-check"></i><b>3.1.2</b> Relative Frequency Distribution</a></li>
<li class="chapter" data-level="3.1.3" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#bargraph"><i class="fa fa-check"></i><b>3.1.3</b> Bargraph</a></li>
<li class="chapter" data-level="3.1.4" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#categorical-statistics"><i class="fa fa-check"></i><b>3.1.4</b> Categorical Statistics</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#quantitative-data"><i class="fa fa-check"></i><b>3.2</b> Quantitative Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#frequency-distribution-1"><i class="fa fa-check"></i><b>3.2.1</b> Frequency Distribution</a></li>
<li class="chapter" data-level="3.2.2" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#histogram"><i class="fa fa-check"></i><b>3.2.2</b> Histogram</a></li>
<li class="chapter" data-level="3.2.3" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#scatterplot"><i class="fa fa-check"></i><b>3.2.3</b> Scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#numerical-measures"><i class="fa fa-check"></i><b>3.3</b> Numerical Measures</a><ul>
<li class="chapter" data-level="3.3.1" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#mean"><i class="fa fa-check"></i><b>3.3.1</b> Mean</a></li>
<li class="chapter" data-level="3.3.2" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#median"><i class="fa fa-check"></i><b>3.3.2</b> Median</a></li>
<li class="chapter" data-level="3.3.3" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#quartile"><i class="fa fa-check"></i><b>3.3.3</b> Quartile</a></li>
<li class="chapter" data-level="3.3.4" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#variance"><i class="fa fa-check"></i><b>3.3.4</b> Variance</a></li>
<li class="chapter" data-level="3.3.5" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#standard-deviation"><i class="fa fa-check"></i><b>3.3.5</b> Standard Deviation</a></li>
<li class="chapter" data-level="3.3.6" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#covariance"><i class="fa fa-check"></i><b>3.3.6</b> Covariance</a></li>
<li class="chapter" data-level="3.3.7" data-path="descriptive-analysis-in-r.html"><a href="descriptive-analysis-in-r.html#correlation-coefficient"><i class="fa fa-check"></i><b>3.3.7</b> Correlation Coefficient</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-distribution-in-r.html"><a href="probability-distribution-in-r.html"><i class="fa fa-check"></i><b>4</b> Probability Distribution in R</a><ul>
<li class="chapter" data-level="4.1" data-path="probability-distribution-in-r.html"><a href="probability-distribution-in-r.html#continuous-uniform-distribution"><i class="fa fa-check"></i><b>4.1</b> Continuous Uniform Distribution</a></li>
<li class="chapter" data-level="4.2" data-path="probability-distribution-in-r.html"><a href="probability-distribution-in-r.html#normal-distribution"><i class="fa fa-check"></i><b>4.2</b> Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estimation-of-mean-in-r.html"><a href="estimation-of-mean-in-r.html"><i class="fa fa-check"></i><b>5</b> Estimation of Mean in R</a><ul>
<li class="chapter" data-level="5.1" data-path="estimation-of-mean-in-r.html"><a href="estimation-of-mean-in-r.html#point-estimation-of-the-population-mean"><i class="fa fa-check"></i><b>5.1</b> Point Estimation of the Population Mean</a></li>
<li class="chapter" data-level="5.2" data-path="estimation-of-mean-in-r.html"><a href="estimation-of-mean-in-r.html#interval-estimate-of-population-mean-with-known-variance"><i class="fa fa-check"></i><b>5.2</b> Interval Estimate of Population Mean with Known Variance</a></li>
<li class="chapter" data-level="5.3" data-path="estimation-of-mean-in-r.html"><a href="estimation-of-mean-in-r.html#interval-estimate-of-population-mean-with-unknown-variance"><i class="fa fa-check"></i><b>5.3</b> Interval Estimate of Population Mean with Unknown Variance</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html"><i class="fa fa-check"></i><b>6</b> Hypothesis Testing in R</a><ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#lower-tail-test-of-population-mean-with-known-variance"><i class="fa fa-check"></i><b>6.1</b> Lower Tail Test of Population Mean with Known Variance</a></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#two-tailed-test-of-population-mean-with-known-variance"><i class="fa fa-check"></i><b>6.2</b> Two-Tailed Test of Population Mean with Known Variance</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#lower-tail-test-of-population-mean-with-unknown-variance"><i class="fa fa-check"></i><b>6.3</b> Lower Tail Test of Population Mean with Unknown Variance</a></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#two-tailed-test-of-population-mean-with-unknown-variance"><i class="fa fa-check"></i><b>6.4</b> Two-Tailed Test of Population Mean with Unknown Variance</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html"><i class="fa fa-check"></i><b>7</b> Simple Regression in R</a><ul>
<li class="chapter" data-level="7.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#estimating-a-simple-linear-regression-model"><i class="fa fa-check"></i><b>7.1</b> Estimating a Simple Linear Regression Model</a></li>
<li class="chapter" data-level="7.2" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#coefficients-of-determination"><i class="fa fa-check"></i><b>7.2</b> Coefficients of Determination</a><ul>
<li class="chapter" data-level="7.2.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#significance-test-of-simple-linear-regression"><i class="fa fa-check"></i><b>7.2.1</b> Significance Test of Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#confidence-interval-for-simple-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Confidence Interval for Simple Linear Regression</a></li>
<li class="chapter" data-level="7.4" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#prediction-interval-for-simple-linear-regression"><i class="fa fa-check"></i><b>7.4</b> Prediction Interval for Simple Linear Regression</a></li>
<li class="chapter" data-level="7.5" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#residual-plot"><i class="fa fa-check"></i><b>7.5</b> Residual Plot</a><ul>
<li class="chapter" data-level="7.5.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#reproducible-reports-using-rmarkdown"><i class="fa fa-check"></i><b>7.5.1</b> Reproducible Reports using Rmarkdown</a></li>
<li class="chapter" data-level="7.5.2" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#integration-with-cc-using-rcpp"><i class="fa fa-check"></i><b>7.5.2</b> Integration with C/C++ using Rcpp</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="production.html"><a href="production.html"><i class="fa fa-check"></i><b>8</b> Production and Cost Function Estimation</a><ul>
<li class="chapter" data-level="8.1" data-path="production.html"><a href="production.html#motivations"><i class="fa fa-check"></i><b>8.1</b> Motivations</a><ul>
<li class="chapter" data-level="8.1.1" data-path="production.html"><a href="production.html#io"><i class="fa fa-check"></i><b>8.1.1</b> IO</a></li>
<li class="chapter" data-level="8.1.2" data-path="production.html"><a href="production.html#development"><i class="fa fa-check"></i><b>8.1.2</b> Development</a></li>
<li class="chapter" data-level="8.1.3" data-path="production.html"><a href="production.html#trade"><i class="fa fa-check"></i><b>8.1.3</b> Trade</a></li>
<li class="chapter" data-level="8.1.4" data-path="production.html"><a href="production.html#management"><i class="fa fa-check"></i><b>8.1.4</b> Management</a></li>
<li class="chapter" data-level="8.1.5" data-path="production.html"><a href="production.html#education"><i class="fa fa-check"></i><b>8.1.5</b> Education</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="production.html"><a href="production.html#analyzing-producer-behaviors"><i class="fa fa-check"></i><b>8.2</b> Analyzing Producer Behaviors</a></li>
<li class="chapter" data-level="8.3" data-path="production.html"><a href="production.html#production-function-estimation"><i class="fa fa-check"></i><b>8.3</b> Production Function Estimation</a><ul>
<li class="chapter" data-level="8.3.1" data-path="production.html"><a href="production.html#cobb-douglas-specification-as-a-benchmark"><i class="fa fa-check"></i><b>8.3.1</b> Cobb-Douglas Specification as a Benchmark</a></li>
<li class="chapter" data-level="8.3.2" data-path="production.html"><a href="production.html#potential-bias-i-endogeneity"><i class="fa fa-check"></i><b>8.3.2</b> Potential Bias I: Endogeneity</a></li>
<li class="chapter" data-level="8.3.3" data-path="production.html"><a href="production.html#potential-bias-ii-selection"><i class="fa fa-check"></i><b>8.3.3</b> Potential Bias II: Selection</a></li>
<li class="chapter" data-level="8.3.4" data-path="production.html"><a href="production.html#how-to-resolve-endogeneity-bias"><i class="fa fa-check"></i><b>8.3.4</b> How to Resolve Endogeneity Bias?</a></li>
<li class="chapter" data-level="8.3.5" data-path="production.html"><a href="production.html#panel-data"><i class="fa fa-check"></i><b>8.3.5</b> Panel Data</a></li>
<li class="chapter" data-level="8.3.6" data-path="production.html"><a href="production.html#first-order-condition-for-inputs"><i class="fa fa-check"></i><b>8.3.6</b> First-Order Condition for Inputs</a></li>
<li class="chapter" data-level="8.3.7" data-path="production.html"><a href="production.html#productioniv"><i class="fa fa-check"></i><b>8.3.7</b> Instrumental Variable</a></li>
<li class="chapter" data-level="8.3.8" data-path="production.html"><a href="production.html#olley-pakes-approach"><i class="fa fa-check"></i><b>8.3.8</b> Olley-Pakes Approach</a></li>
<li class="chapter" data-level="8.3.9" data-path="production.html"><a href="production.html#assumption-i-information-set"><i class="fa fa-check"></i><b>8.3.9</b> Assumption I: Information Set</a></li>
<li class="chapter" data-level="8.3.10" data-path="production.html"><a href="production.html#assumption-ii-first-order-markov"><i class="fa fa-check"></i><b>8.3.10</b> Assumption II: First Order Markov</a></li>
<li class="chapter" data-level="8.3.11" data-path="production.html"><a href="production.html#assumption-iii-timing-of-input-choices"><i class="fa fa-check"></i><b>8.3.11</b> Assumption III: Timing of Input Choices</a></li>
<li class="chapter" data-level="8.3.12" data-path="production.html"><a href="production.html#assumption-iv-scalar-unobservable"><i class="fa fa-check"></i><b>8.3.12</b> Assumption IV: Scalar Unobservable</a></li>
<li class="chapter" data-level="8.3.13" data-path="production.html"><a href="production.html#assumption-iv-strict-monotonicity"><i class="fa fa-check"></i><b>8.3.13</b> Assumption IV: Strict Monotonicity</a></li>
<li class="chapter" data-level="8.3.14" data-path="production.html"><a href="production.html#two-step-approach-the-first-step"><i class="fa fa-check"></i><b>8.3.14</b> Two-step Approach: The First Step</a></li>
<li class="chapter" data-level="8.3.15" data-path="production.html"><a href="production.html#two-step-approach-the-second-step"><i class="fa fa-check"></i><b>8.3.15</b> Two-step Approach: The Second Step</a></li>
<li class="chapter" data-level="8.3.16" data-path="production.html"><a href="production.html#identification-of-the-anticipated-shocks"><i class="fa fa-check"></i><b>8.3.16</b> Identification of the Anticipated Shocks</a></li>
<li class="chapter" data-level="8.3.17" data-path="production.html"><a href="production.html#two-step-estimation-of-olley1996."><i class="fa fa-check"></i><b>8.3.17</b> Two-Step Estimation of <span class="citation">Olley &amp; Pakes (<a href="#ref-Olley1996">1996</a>)</span>.</a></li>
<li class="chapter" data-level="8.3.18" data-path="production.html"><a href="production.html#from-an-economic-models-to-an-econometric-model"><i class="fa fa-check"></i><b>8.3.18</b> From An Economic Models to An Econometric Model</a></li>
<li class="chapter" data-level="8.3.19" data-path="production.html"><a href="production.html#how-to-resolve-selection-bias"><i class="fa fa-check"></i><b>8.3.19</b> How to Resolve Selection Bias</a></li>
<li class="chapter" data-level="8.3.20" data-path="production.html"><a href="production.html#correction-in-the-first-step"><i class="fa fa-check"></i><b>8.3.20</b> Correction in the First Step</a></li>
<li class="chapter" data-level="8.3.21" data-path="production.html"><a href="production.html#correction-in-the-second-step-i-the-source-of-bias"><i class="fa fa-check"></i><b>8.3.21</b> Correction in the Second Step I: The Source of Bias</a></li>
<li class="chapter" data-level="8.3.22" data-path="production.html"><a href="production.html#correction-in-the-second-step-ii-conditional-exit-probability"><i class="fa fa-check"></i><b>8.3.22</b> Correction in the Second Step II: Conditional Exit Probability</a></li>
<li class="chapter" data-level="8.3.23" data-path="production.html"><a href="production.html#correction-in-the-second-step-iii-invertibility-in-threshold"><i class="fa fa-check"></i><b>8.3.23</b> Correction in the Second Step III: Invertibility in Threshold</a></li>
<li class="chapter" data-level="8.3.24" data-path="production.html"><a href="production.html#correction-in-the-second-step-iv-controlling-the-threshold"><i class="fa fa-check"></i><b>8.3.24</b> Correction in the Second Step IV: Controlling the Threshold</a></li>
<li class="chapter" data-level="8.3.25" data-path="production.html"><a href="production.html#three-step-estimation-of-olley1996"><i class="fa fa-check"></i><b>8.3.25</b> Three Step Estimation of <span class="citation">Olley &amp; Pakes (<a href="#ref-Olley1996">1996</a>)</span></a></li>
<li class="chapter" data-level="8.3.26" data-path="production.html"><a href="production.html#zero-investment-problem"><i class="fa fa-check"></i><b>8.3.26</b> Zero Investment Problem</a></li>
<li class="chapter" data-level="8.3.27" data-path="production.html"><a href="production.html#tackle-zero-investment-problem-i-discard-some-data"><i class="fa fa-check"></i><b>8.3.27</b> Tackle Zero Investment Problem I: Discard Some Data</a></li>
<li class="chapter" data-level="8.3.28" data-path="production.html"><a href="production.html#tackle-zero-investment-problem-ii-use-another-proxy"><i class="fa fa-check"></i><b>8.3.28</b> Tackle Zero Investment Problem II: Use Another Proxy</a></li>
<li class="chapter" data-level="8.3.29" data-path="production.html"><a href="production.html#one-step-estimation-of-olley1996-and-levinsohn2003"><i class="fa fa-check"></i><b>8.3.29</b> One-step Estimation of <span class="citation">Olley &amp; Pakes (<a href="#ref-Olley1996">1996</a>)</span> and <span class="citation">Levinsohn &amp; Petrin (<a href="#ref-Levinsohn2003">2003</a>)</span></a></li>
<li class="chapter" data-level="8.3.30" data-path="production.html"><a href="production.html#scalar-unobservable-problem-finite-order-markov-process"><i class="fa fa-check"></i><b>8.3.30</b> Scalar Unobservable Problem: Finite-order Markov Process</a></li>
<li class="chapter" data-level="8.3.31" data-path="production.html"><a href="production.html#scalar-unobservable-problem-demand-and-productivity-shocks"><i class="fa fa-check"></i><b>8.3.31</b> Scalar Unobservable Problem: Demand and Productivity Shocks</a></li>
<li class="chapter" data-level="8.3.32" data-path="production.html"><a href="production.html#collinearity-problem"><i class="fa fa-check"></i><b>8.3.32</b> Collinearity Problem</a></li>
<li class="chapter" data-level="8.3.33" data-path="production.html"><a href="production.html#tackle-collinearity-problem-peculiar-assumptions"><i class="fa fa-check"></i><b>8.3.33</b> Tackle Collinearity Problem: Peculiar Assumptions</a></li>
<li class="chapter" data-level="8.3.34" data-path="production.html"><a href="production.html#tackle-collinearity-problem-share-regression"><i class="fa fa-check"></i><b>8.3.34</b> Tackle Collinearity Problem: Share Regression</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="production.html"><a href="production.html#cost-function-estimation"><i class="fa fa-check"></i><b>8.4</b> Cost Function Estimation</a><ul>
<li class="chapter" data-level="8.4.1" data-path="production.html"><a href="production.html#cost-function-duality"><i class="fa fa-check"></i><b>8.4.1</b> Cost Function: Duality</a></li>
<li class="chapter" data-level="8.4.2" data-path="production.html"><a href="production.html#translog-cost-function"><i class="fa fa-check"></i><b>8.4.2</b> Translog Cost Function</a></li>
<li class="chapter" data-level="8.4.3" data-path="production.html"><a href="production.html#translog-cost-function-integrability"><i class="fa fa-check"></i><b>8.4.3</b> Translog Cost Function: Integrability</a></li>
<li class="chapter" data-level="8.4.4" data-path="production.html"><a href="production.html#two-approaches"><i class="fa fa-check"></i><b>8.4.4</b> Two Approaches</a></li>
<li class="chapter" data-level="8.4.5" data-path="production.html"><a href="production.html#cost-data-approach"><i class="fa fa-check"></i><b>8.4.5</b> Cost Data Approach</a></li>
<li class="chapter" data-level="8.4.6" data-path="production.html"><a href="production.html#revealed-preference-approach"><i class="fa fa-check"></i><b>8.4.6</b> Revealed Preference Approach</a></li>
<li class="chapter" data-level="8.4.7" data-path="production.html"><a href="production.html#single-product-monopolist"><i class="fa fa-check"></i><b>8.4.7</b> Single-product Monopolist</a></li>
<li class="chapter" data-level="8.4.8" data-path="production.html"><a href="production.html#unobserved-heterogeneity-in-the-cost-function"><i class="fa fa-check"></i><b>8.4.8</b> Unobserved Heterogeneity in the Cost Function</a></li>
<li class="chapter" data-level="8.4.9" data-path="production.html"><a href="production.html#multi-product-monopolist-case"><i class="fa fa-check"></i><b>8.4.9</b> Multi-product Monopolist Case</a></li>
<li class="chapter" data-level="8.4.10" data-path="production.html"><a href="production.html#oligopoly"><i class="fa fa-check"></i><b>8.4.10</b> Oligopoly</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ECON 6120I Topics in Empirical Industrial Organization</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hypothesis-testing-in-r" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Hypothesis Testing in R</h1>
<div id="lower-tail-test-of-population-mean-with-known-variance" class="section level2">
<h2><span class="header-section-number">6.1</span> Lower Tail Test of Population Mean with Known Variance</h2>
<ul>
<li><p>The null hypothesis of the lower tail test of the population mean can be expressed as follows: <span class="math display">\[
\mu \ge \mu_0
\]</span> where <span class="math inline">\(\mu_0\)</span> is a hypothesized lower bound of the true population mean <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>Let us define the test statistic <span class="math inline">\(z\)</span> in terms of the sample mean, the sample size and the population standard deviation σ : <span class="math display">\[
z = \frac{\overline{x} - \mu_0}{\sigma/\sqrt{N}}.
\]</span></p></li>
<li><p>Then the null hypothesis of the lower tail test is to be rejected if <span class="math inline">\(z \le z_{\alpha}\)</span> , where <span class="math inline">\(z_{\alpha}\)</span> is the <span class="math inline">\(100(1 − \alpha)\)</span> percentile of the standard normal distribution.</p></li>
<li><p>Problem: Suppose the manufacturer claims that the mean lifetime of a light bulb is more than 10,000 hours. In a sample of 30 light bulbs, it was found that they only last 9,900 hours on average. Assume the population standard deviation is 120 hours. At .05 significance level, can we reject the claim by the manufacturer?</p></li>
<li><p>Solution: The null hypothesis is that <span class="math inline">\(\mu \ge 10000 = \mu_0\)</span>. We begin with computing the test statistic.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xbar &lt;-<span class="st"> </span><span class="dv">9900</span>            <span class="co"># sample mean </span>
mu0 &lt;-<span class="st"> </span><span class="dv">10000</span>            <span class="co"># hypothesized value </span>
sigma &lt;-<span class="st"> </span><span class="dv">120</span>            <span class="co"># population standard deviation </span>
N &lt;-<span class="st"> </span><span class="dv">30</span>                 <span class="co"># sample size </span>
z &lt;-<span class="st"> </span>(xbar <span class="op">-</span><span class="st"> </span>mu0)<span class="op">/</span>(sigma<span class="op">/</span><span class="kw">sqrt</span>(N)) 
z                      <span class="co"># test statistic </span></code></pre></div>
<pre><code>## [1] -4.564355</code></pre>
<ul>
<li>We then compute the critical value at .05 significance level.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alpha &lt;-<span class="st"> </span>.<span class="dv">05</span> 
z_alpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha) 
<span class="op">-</span><span class="st"> </span>z_alpha               <span class="co"># critical value </span></code></pre></div>
<pre><code>## [1] -1.644854</code></pre>
<ul>
<li>The test statistic -4.5644 is less than the critical value of -1.6449. Hence, at .05 significance level, we reject the claim that mean lifetime of a light bulb is above 10,000 hours.</li>
</ul>
</div>
<div id="two-tailed-test-of-population-mean-with-known-variance" class="section level2">
<h2><span class="header-section-number">6.2</span> Two-Tailed Test of Population Mean with Known Variance</h2>
<ul>
<li><p>The null hypothesis of the two-tailed test of the population mean can be expressed as follows: <span class="math display">\[
\mu = \mu_0
\]</span> where <span class="math inline">\(\mu_0\)</span> is a hypothesized value of the true population mean <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>Let us define the test statistic <span class="math inline">\(z\)</span> in terms of the sample mean, the sample size and the population standard deviation <span class="math inline">\(\sigma\)</span>: <span class="math display">\[
z = \frac{\overline{x} - \mu_0}{\sigma/\sqrt{N}}
\]</span></p></li>
<li><p>Then the null hypothesis of the two-tailed test is to be rejected if <span class="math inline">\(z \le - z_{\alpha/2}\)</span> or <span class="math inline">\(z \ge z_{\alpha/2}\)</span>, where <span class="math inline">\(z_{\alpha/2}\)</span> is the <span class="math inline">\(100(1 - \alpha∕2)\)</span> percentile of the standard normal distribution.</p></li>
<li><p>Problem: Suppose the mean weight of King Penguins found in an Antarctic colony last year was 15.4 kg. In a sample of 35 penguins same time this year in the same colony, the mean penguin weight is 14.6 kg. Assume the population standard deviation is 2.5 kg. At .05 significance level, can we reject the null hypothesis that the mean penguin weight does not differ from last year?</p></li>
<li><p>Solution: The null hypothesis is that <span class="math inline">\(\mu = 15.4 = \mu_0\)</span>. We begin with computing the test statistic.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xbar &lt;-<span class="st"> </span><span class="fl">14.6</span>            <span class="co"># sample mean </span>
mu0 &lt;-<span class="st"> </span><span class="fl">15.4</span>             <span class="co"># hypothesized value </span>
sigma &lt;-<span class="st"> </span><span class="fl">2.5</span>            <span class="co"># population standard deviation </span>
N &lt;-<span class="st"> </span><span class="dv">35</span>                 <span class="co"># sample size </span>
z &lt;-<span class="st"> </span>(xbar <span class="op">-</span><span class="st"> </span>mu0)<span class="op">/</span>(sigma<span class="op">/</span><span class="kw">sqrt</span>(N)) 
z                      <span class="co"># test statistic </span></code></pre></div>
<pre><code>## [1] -1.893146</code></pre>
<ul>
<li>We then compute the critical values at .05 significance level.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alpha &lt;-<span class="st"> </span>.<span class="dv">05</span> 
z_half_alpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha<span class="op">/</span><span class="dv">2</span>) 
<span class="kw">c</span>(<span class="op">-</span><span class="st"> </span>z_half_alpha, z_half_alpha) </code></pre></div>
<pre><code>## [1] -1.959964  1.959964</code></pre>
<ul>
<li>The test statistic -1.8931 lies between the critical values -1.9600 and 1.9600. Hence, at .05 significance level, we do not reject the null hypothesis that the mean penguin weight does not differ from last year.</li>
</ul>
</div>
<div id="lower-tail-test-of-population-mean-with-unknown-variance" class="section level2">
<h2><span class="header-section-number">6.3</span> Lower Tail Test of Population Mean with Unknown Variance</h2>
<ul>
<li><p>The null hypothesis of the lower tail test of the population mean can be expressed as follows: <span class="math display">\[
\mu \ge \mu_0
\]</span> where <span class="math inline">\(\mu_0\)</span> is a hypothesized lower bound of the true population mean <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>Let us define the test statistic <span class="math inline">\(t\)</span> in terms of the sample mean, the sample size and the sample standard deviation <span class="math inline">\(s\)</span>: <span class="math display">\[
t = \frac{\overline{x} - \mu_0}{s/\sqrt{N}}
\]</span></p></li>
<li><p>Then the null hypothesis of the lower tail test is to be rejected if <span class="math inline">\(t \le - t_{N - 1, \alpha}\)</span>, where <span class="math inline">\(t_{N - 1, \alpha}\)</span> is the <span class="math inline">\(100(1 − \alpha)\)</span> percentile of the Student <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(N − 1\)</span> degrees of freedom.</p></li>
<li><p>Problem: A teacher claims that the average height of the students is higher than 174. At .05 significance level, can we reject the claim by the teacher without assuming the population standard deviation of the student height in survey?</p></li>
<li><p>Solution: The null hypothesis is that <span class="math inline">\(\mu \ge 174 = \mu_0\)</span>. We begin with computing the test statistic.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)                  <span class="co"># load the MASS package </span>
height_response &lt;-<span class="st"> </span><span class="kw">na.omit</span>(survey<span class="op">$</span>Height)
xbar &lt;-<span class="st"> </span><span class="kw">mean</span>(height_response)            <span class="co"># sample mean </span>
mu0 &lt;-<span class="st"> </span><span class="dv">174</span>            <span class="co"># hypothesized value </span>
s &lt;-<span class="st"> </span><span class="kw">sd</span>(height_response)                <span class="co"># sample standard deviation </span>
N &lt;-<span class="st"> </span><span class="kw">length</span>(height_response)                <span class="co"># sample size </span>
t &lt;-<span class="st"> </span>(xbar <span class="op">-</span><span class="st"> </span>mu0)<span class="op">/</span>(s<span class="op">/</span><span class="kw">sqrt</span>(N)) 
t</code></pre></div>
<pre><code>## [1] -2.377004</code></pre>
<ul>
<li>We then compute the critical value at .05 significance level.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alpha &lt;-<span class="st"> </span>.<span class="dv">05</span> 
t_alpha &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha, <span class="dt">df =</span> N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) 
<span class="op">-</span><span class="st"> </span>t_alpha</code></pre></div>
<pre><code>## [1] -1.652212</code></pre>
<ul>
<li><p>The test statistic -2.3770045 is less than the critical value of -1.6522124. Hence, at .05 significance level, we can reject the claim that the average height is above 174.</p></li>
<li><p>Library Solution: Instead of using the textbook formula, we can apply the t.test function in the built-in stats package.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(height_response,
       <span class="dt">alternative =</span> <span class="st">&quot;less&quot;</span>,
       <span class="dt">mu =</span> <span class="dv">174</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  height_response
## t = -2.377, df = 208, p-value = 0.00918
## alternative hypothesis: true mean is less than 174
## 95 percent confidence interval:
##      -Inf 173.5063
## sample estimates:
## mean of x 
##  172.3809</code></pre>
</div>
<div id="two-tailed-test-of-population-mean-with-unknown-variance" class="section level2">
<h2><span class="header-section-number">6.4</span> Two-Tailed Test of Population Mean with Unknown Variance</h2>
<ul>
<li><p>The null hypothesis of the two-tailed test of the population mean can be expressed as follows: <span class="math display">\[
\mu = \mu_0
\]</span> where <span class="math inline">\(\mu_0\)</span> is a hypothesized value of the true population mean <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>Let us define the test statistic <span class="math inline">\(t\)</span> in terms of the sample mean, the sample size and the sample standard deviation <span class="math inline">\(s\)</span>: <span class="math display">\[
t = \frac{\overline{x} - \mu_0}{s/\sqrt{N}}
\]</span></p></li>
<li><p>Then the null hypothesis of the two-tailed test is to be rejected if <span class="math inline">\(t \le - t_{N - 1, \alpha/2}\)</span> or <span class="math inline">\(t \ge t_{N - 1, \alpha/2}\)</span>, where <span class="math inline">\(t_{N - 1, \alpha/2}\)</span> is the <span class="math inline">\(100(1 - \alpha)\)</span> percentile of the Student <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(N - 1\)</span> degrees of freedom.</p></li>
<li><p>Problem: A teacher claims that the average height of the students is equal to 173. At .05 significance level, can we reject the claim by the teacher without assuming the population standard deviation of the student height in survey?</p></li>
<li><p>Solution: The null hypothesis is that <span class="math inline">\(\mu = 173 = \mu_0\)</span>. We begin with computing the test statistic.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)                  <span class="co"># load the MASS package </span>
height_response &lt;-<span class="st"> </span><span class="kw">na.omit</span>(survey<span class="op">$</span>Height)
xbar &lt;-<span class="st"> </span><span class="kw">mean</span>(height_response)            <span class="co"># sample mean </span>
mu0 &lt;-<span class="st"> </span><span class="dv">173</span>            <span class="co"># hypothesized value </span>
s &lt;-<span class="st"> </span><span class="kw">sd</span>(height_response)                <span class="co"># sample standard deviation </span>
N &lt;-<span class="st"> </span><span class="kw">length</span>(height_response)                <span class="co"># sample size </span>
t &lt;-<span class="st"> </span>(xbar <span class="op">-</span><span class="st"> </span>mu0)<span class="op">/</span>(s<span class="op">/</span><span class="kw">sqrt</span>(N)) 
t</code></pre></div>
<pre><code>## [1] -0.9089373</code></pre>
<ul>
<li>We then compute the critical value at .05 significance level.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alpha &lt;-<span class="st"> </span>.<span class="dv">05</span> 
t_half_alpha &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha<span class="op">/</span><span class="dv">2</span>, <span class="dt">df =</span> N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) 
<span class="kw">c</span>(<span class="op">-</span><span class="st"> </span>t_half_alpha, t_half_alpha)</code></pre></div>
<pre><code>## [1] -1.971435  1.971435</code></pre>
<ul>
<li><p>The test statistic -0.9089373 is between the critical values of -1.9714347 and 1.9714347. Hence, at .05 significance level, we cannot reject the claim that the average height is equal to 173.</p></li>
<li><p>Library Solution: Instead of using the textbook formula, we can apply the t.test function in the built-in stats package.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(height_response,
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,
       <span class="dt">mu =</span> <span class="dv">173</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  height_response
## t = -0.90894, df = 208, p-value = 0.3644
## alternative hypothesis: true mean is not equal to 173
## 95 percent confidence interval:
##  171.0380 173.7237
## sample estimates:
## mean of x 
##  172.3809</code></pre>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estimation-of-mean-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="simple-regression-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["lecture.pdf", "lecture.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
