# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_square_rcpp2 <- function(x) {
    .Call('_EmpiricalIO_compute_square_rcpp2', PACKAGE = 'EmpiricalIO', x)
}

compute_square_rcpp <- function(x) {
    .Call('_EmpiricalIO_compute_square_rcpp', PACKAGE = 'EmpiricalIO', x)
}

pass_numeric_vector_to_rcpp <- function(x) {
    .Call('_EmpiricalIO_pass_numeric_vector_to_rcpp', PACKAGE = 'EmpiricalIO', x)
}

pass_numeric_matrix_to_rcpp <- function(Y) {
    .Call('_EmpiricalIO_pass_numeric_matrix_to_rcpp', PACKAGE = 'EmpiricalIO', Y)
}

pass_integer_vector_to_rcpp <- function(z) {
    .Call('_EmpiricalIO_pass_integer_vector_to_rcpp', PACKAGE = 'EmpiricalIO', z)
}

pass_integer_matrix_to_rcpp <- function(W) {
    .Call('_EmpiricalIO_pass_integer_matrix_to_rcpp', PACKAGE = 'EmpiricalIO', W)
}

pass_list_to_rcpp <- function(L) {
    .Call('_EmpiricalIO_pass_list_to_rcpp', PACKAGE = 'EmpiricalIO', L)
}

pass_data_frame_to_rcpp <- function(D) {
    .Call('_EmpiricalIO_pass_data_frame_to_rcpp', PACKAGE = 'EmpiricalIO', D)
}

pass_numeric_vector_to_eigen <- function(x) {
    .Call('_EmpiricalIO_pass_numeric_vector_to_eigen', PACKAGE = 'EmpiricalIO', x)
}

pass_numeric_matrix_to_eigen <- function(Y) {
    .Call('_EmpiricalIO_pass_numeric_matrix_to_eigen', PACKAGE = 'EmpiricalIO', Y)
}

pass_integer_vector_to_eigen <- function(z) {
    .Call('_EmpiricalIO_pass_integer_vector_to_eigen', PACKAGE = 'EmpiricalIO', z)
}

pass_integer_matrix_to_eigen <- function(W) {
    .Call('_EmpiricalIO_pass_integer_matrix_to_eigen', PACKAGE = 'EmpiricalIO', W)
}

map_numeric_vector_to_eigen <- function(x) {
    .Call('_EmpiricalIO_map_numeric_vector_to_eigen', PACKAGE = 'EmpiricalIO', x)
}

map_numeric_matrix_to_eigen <- function(Y) {
    .Call('_EmpiricalIO_map_numeric_matrix_to_eigen', PACKAGE = 'EmpiricalIO', Y)
}

pass_list_to_eigen <- function(L) {
    .Call('_EmpiricalIO_pass_list_to_eigen', PACKAGE = 'EmpiricalIO', L)
}

pass_named_list_to_eigen <- function(L) {
    .Call('_EmpiricalIO_pass_named_list_to_eigen', PACKAGE = 'EmpiricalIO', L)
}

extract_column_from_data_frame <- function(D) {
    .Call('_EmpiricalIO_extract_column_from_data_frame', PACKAGE = 'EmpiricalIO', D)
}

matrix_vector_arithmetic_rcpp <- function(A, B, v, c) {
    .Call('_EmpiricalIO_matrix_vector_arithmetic_rcpp', PACKAGE = 'EmpiricalIO', A, B, v, c)
}

coefficientwise_operation_rcpp <- function(A, B, r) {
    .Call('_EmpiricalIO_coefficientwise_operation_rcpp', PACKAGE = 'EmpiricalIO', A, B, r)
}

solve_least_squares_svd <- function(A, B) {
    .Call('_EmpiricalIO_solve_least_squares_svd', PACKAGE = 'EmpiricalIO', A, B)
}

solve_least_squares_qr <- function(A, B) {
    .Call('_EmpiricalIO_solve_least_squares_qr', PACKAGE = 'EmpiricalIO', A, B)
}

access_rcpp <- function(A, i, j) {
    .Call('_EmpiricalIO_access_rcpp', PACKAGE = 'EmpiricalIO', A, i, j)
}

rcppeigen_hello_world <- function() {
    .Call('_EmpiricalIO_rcppeigen_hello_world', PACKAGE = 'EmpiricalIO')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_EmpiricalIO_rcppeigen_outerproduct', PACKAGE = 'EmpiricalIO', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_EmpiricalIO_rcppeigen_innerproduct', PACKAGE = 'EmpiricalIO', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_EmpiricalIO_rcppeigen_bothproducts', PACKAGE = 'EmpiricalIO', x)
}

