# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_EmpiricalIO_timesTwo', PACKAGE = 'EmpiricalIO', x)
}

minus2_rcpp <- function(x) {
    .Call('_EmpiricalIO_minus2_rcpp', PACKAGE = 'EmpiricalIO', x)
}

rcppeigen_hello_world <- function() {
    .Call('_EmpiricalIO_rcppeigen_hello_world', PACKAGE = 'EmpiricalIO')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_EmpiricalIO_rcppeigen_outerproduct', PACKAGE = 'EmpiricalIO', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_EmpiricalIO_rcppeigen_innerproduct', PACKAGE = 'EmpiricalIO', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_EmpiricalIO_rcppeigen_bothproducts', PACKAGE = 'EmpiricalIO', x)
}

